version: '3.2'
name: birn-platform

services:
  postgres:
    image: postgres:13-alpine
    container_name: dflow-postgres
    volumes:
      - vol-postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Dfl0w}
      # - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      # - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432
    networks:
      - birn-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rest-api:
    image: birn-api:0.1.0
    container_name: rest-api
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - birn-net
    restart: unless-stopped
    command: ["uvicorn", "app.api.server:app", "--reload", "--workers", "1", "--host", "0.0.0.0", "--port", "8000"]

networks:
  birn-net:
    driver: bridge
    name: "birn-net"

volumes:
  db-data:
    name: db-data
    driver: local
    driver_opts: {}
