---
version: '3.9'
# name: ''

services:
  emqx:
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=emqx.local
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    # ports:
    #   - "1883:1883"  # mqtt:tcp
    #   - "8883:8883"  # mqtt:tcp:ssl
    #   - "8083:8083"  # mqtt:ws
    #   - "8084:8084"  # mqtt:ws:ssl
    #   - "8081:8081"  # http:management
    #   - "18083:18083"  # http:dashboard
    #   - "61613:61613"  # web-stomp gateway
    networks:
      tv-wh-mqtt:
        aliases:
        - emqx.local
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

  tradingview-webhook-mqtt-bridge:
    build: .
    container_name: tradingview-webhook-mqtt-bridge
    restart: unless-stopped
    depends_on:
      emqx:
        condition: service_healthy
        restart: true
    ports:
      - '80:8080'
    environment:
      - MQTT_HOST=emqx.local
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_TOPIC=tv_alerts
    command: [
      "uvicorn",
      "app:app",
      "--workers", "4",
      "--host", "0.0.0.0",
      "--port", "8080",
      '--root-path', '/']
    networks:
      tv-wh-mqtt:
        aliases:
        - bridge.local


networks:
  tv-wh-mqtt:
    driver: bridge

volumes:
  emqx-data: {}
  emqx-log: {}
  emqx-etc: {}
